all:
	clang -o click click.m -framework ApplicationServices -framework Foundation 
	clang -o press press.m -framework ApplicationServices -framework Foundation 
	clang++ -o app call_click.cpp -std=c++14

